[package]
name = "hello_world"
version = "0.0.1"

[addresses]
my_account = "0x8ac1b8ff9583ac8e661c7f0ee462698c57bb7fc454f587e3fa25a57f9406acc0"

[dependencies]
AxelarFramework = {  git = "https://github.com/axelarnetwork/axelar-local-dev.git", subdir ="aptos/modules/axelar-framework", rev = "a6d1b1ab670f3bbab88e0adb436cf9411ba9eacb" }
